import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from 'next';

import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Icon, { EIcons } from '../../components/Icon/index';
import exampleItems from '../../mocks/playground';

import styles from './playground.module.css';

const PlaygroundOverview: NextPage = () => {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main className={styles.overview}>
      <h1 className={styles.overviewTitle}>Playground</h1>
      <h1 className={styles.overviewSupport}>Simple snippets, or TIL today.</h1>
      { exampleItems.map((item, index) => (
        <Link href={item.link} key={`item--${index}`}>
          <a className={styles.itemCard}>
            <h2 className={styles.itemTitle}>{item.title}</h2>
            <p className={styles.itemDescription}>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga totam id impedit unde velit. Maxime qui eveniet, explicabo.
            </p>
            <div className={styles.itemTaglist}>
              <Icon icon={EIcons.Tag} width={12} height={12} />
              <p className={styles.itemTags}>{item.tags.join(', ')}</p>
            </div>
          </a>
        </Link>
      )) }
    </main>
    <Footer />
  </>;
};

export default PlaygroundOverview;
