import Head from 'next/head';
import type { NextPage } from 'next';

import Header from '../../components/header';
import Footer from '../../components/footer';
import styles from './blog.module.css';
import { useRouter } from 'next/router';

const BlogPost: NextPage = () => {
  const { query } = useRouter();
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main className={styles.main}>
      <h1 className={styles.title}>{ query.slug || 'Blog' }</h1>

      <p className="lead">Sizzle metus urna, da bomb da bomb, izzle et, sollicitudin izzle, fo shizzle. Donizzle izzle, nisi egestizzle check out this malesuada, neque go to hizzle consequat velit, funky fresh i'm in the shizzle libero erizzle izzle purus.</p>
      <p>Lorem ipsum dolor sit amizzle, bow wow wow adipiscing elit. Nullizzle mah nizzle velizzle, boofron volutpizzle, suscipizzle boofron, gangsta crunk, brizzle. Pimpin' crunk tortizzle. Sed erizzle. Tellivizzle izzle phat boom shackalack its fo rizzle tempizzle the bizzle. Mauris pellentesque gizzle izzle phat. Its fo rizzle izzle tortizzle. Pellentesque uhuh ... yih! rhoncizzle crazy. In gangsta habitasse shiznit pot. Uhuh ... yih! dapibizzle. Curabitizzle tellus pimpin', pretizzle eu, mattizzle ac, fo shizzle vitae, nunc. Yippiyo suscipizzle. Integizzle i saw beyonces tizzles and my pizzle went crizzle velit ass ghetto.</p>
      <h3>Lorem ipsum dolor</h3>
      <p>Proin yo mamma purus. Nullizzle the bizzle i saw beyonces tizzles and my pizzle went crizzle shizzlin dizzle et that's the shizzle tincidunt pellentesque. In sizzle ma nizzle. That's the shizzle lectus shizzlin dizzle, things i'm in the shizzle amet, vulputate vitae, condimentum daahng dawg, nunc. Crizzle sit check it out maurizzle. Yippiyo fermentizzle hizzle nunc. Yo mamma vulputate, elizzle fizzle facilisizzle, velit tellizzle cursus justo, sed condimentizzle pizzle brizzle dope enim. Sed fermentizzle away nunc. Pellentesque dignissizzle. In hac stuff platea dictumst. Nizzle gizzle its fo rizzle dui. Donizzle sed diam. Nizzle in rizzle. Fo lobortis, elizzle crunk adipiscing gangsta, massa nulla pretizzle lorizzle, quizzle sure ipsum elizzle funky fresh risus.</p>
      <h4>Sub dolor sit amet</h4>
      <p>Nunc shizzlin dizzle arcu. Shiz ante. Dang the bizzle mauris izzle lectizzle. Morbi et tortizzle. Cras izzle tortor da bomb mi consectetizzle its fo rizzle. Lorizzle ipsizzle dolizzle cool amizzle, fizzle sheezy da bomb. Curabitizzle elit arcu, shiznit nizzle, that's the shizzle izzle, bling bling yippiyo, brizzle. Aliquizzle erizzle volutpat. Donec daahng dawg bow wow wow turpizzle. Suspendisse fo shizzle. Da bomb odio urna, mah nizzle izzle, volutpat vitae, vehicula its fo rizzle, break it down. Ma nizzle mah nizzle orci, congue nec, sodales id, sure ut, orci.</p>

      <p>Aliquam ultrices, sizzle et shizzle my nizzle crocodizzle posuere, gangsta quizzle tempus for sure, sed mollizzle dizzle justo fo shizzle away. Maecenizzle placerizzle, ghetto elementizzle nizzle fermentizzle, shizzlin dizzle mauris for sure felizzle, izzle vehicula go to hizzle velit sed mauris. Pimpin' nulla elizzle, imperdizzle owned, malesuada owned, dope cool, pede. Gangster urna. Black ma nizzle, nulla quizzle cursus gangsta, felis dope black dui, crazy bibendizzle my shizz izzle sure erizzle. Bow wow wow tellivizzle. Rizzle sed we gonna chung egizzle rizzle ornare mofo. Integizzle cursizzle, dawg gangsta auctizzle sollicitudizzle, pede purus sempizzle shizznit, sizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle brizzle mi felizzle that's the shizzle massa. Crizzle id its fo rizzle. The bizzle check it out habitasse platea dictumst. Pizzle fo shizzle fizzle, faucibizzle ac, dawg , congue mofo, its fo rizzle. Ma nizzle tellizzle sizzle, molestie pot, gangsta shiznit, shiznit funky fresh, leo. Ma nizzle izzle ghetto izzle yippiyo pulvinizzle dope. Shizznit ipsizzle gangster ass amizzle, consectetizzle adipiscing elit.</p>
      <h3>Nulla aliquam</h3>
      <p>Nulla eu ligula. Boom shackalack go to hizzle commodo tellus. Aenean viverra, cool izzle pot hendrerit, the bizzle urna black leo, non bizzle nunc doggy boom shackalack nunc. Dizzle eu dolor. Vestibulum we gonna chung felizzle. Sed pizzle fo shizzle eros. Cool nulla , volutpat boofron, volutpat sheezy, hizzle brizzle, shit. Yo bizzle. Own yo' nisi. Curabitur sit tellivizzle leo mofo ante blandit dignissim. Sheezy laorizzle shizzle my nizzle crocodizzle hizzle bizzle own yo'. Fo shizzle tempus that's the shizzle doggy.</p>
    </main>
    <Footer />
  </>;
};

export default BlogPost;
