import Head from 'next/head';
import type { NextPage } from 'next';

import Header from '../../components/header';
import Footer from '../../components/footer';
import styles from './blog.module.css';

const BlogOverview: NextPage = () => {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main className={styles.overview}>
      <h1 className={styles.overviewTitle}>Blogposts</h1>
    </main>
    <Footer />
  </>;
};

export default BlogOverview;
