import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from 'next';

import Header from '../components/header';
import Footer from '../components/footer';
import examplePosts from '../mocks/blog';
import exampleItems from '../mocks/playground';

import styles from './home.module.css';

const Home: NextPage = () => {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <section className={[styles.headerTopography, 'fillSVG'].join(' ')}>
      <div className={styles.headerWrapper}>
        <Header fillBg={false} />
      </div>
    </section>
    <main className={styles.main}>
      <section>
        <h3 className={styles.contentHeading}>
          Recent Blogposts
        </h3>
        { examplePosts.map((post, index) => (
          <Link href={post.link} key={`post--${index}`}>
            <a className={styles.postCard}>
              <h2 className={styles.postTitle}>{post.title}</h2>
              <p className={styles.postIntro}>{post.intro}</p>
              <button className={styles.postButton}>Read More</button>
            </a>
          </Link>
        )) }
      </section>
      <section>
        <div className={styles.sidebar}>
          <h3 className={styles.contentHeading}>
            Playground
          </h3>
          { exampleItems.map((item, index) => (
            <Link href={item.link} key={`item--${index}`}>
              <a className={styles.itemCard}>
                <h2 className={styles.itemTitle}>{item.title}</h2>
                <p className={styles.itemTags}>{item.tags.join(', ')}</p>
              </a>
            </Link>
          )) }
        </div>
      </section>
    </main>
    <Footer />
  </>;
};

export default Home;
