import Head from 'next/head';
import type { NextPage } from 'next';

import Header from '../components/header';
import Footer from '../components/footer';
import styles from './home.module.css';

const Home: NextPage = () => {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main className={styles.main}>
      <p>Main content</p>
    </main>
    <Footer />
  </>;
};

export default Home;
