import Head from 'next/head';
import Link from 'next/link';

import Header from '../../Header';
import Footer from '../../Footer';
import Icon, { EIcons } from '../../Icon';

import type { PlaygroundMeta } from '../../../types';
import type { MDXOverviewPage } from '../../../types/mdx';

import styles from './PlaygroundOverview.module.css';

const PlaygroundOverview: MDXOverviewPage<PlaygroundMeta> = ({ items }) => {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />
    <main className={styles.overview}>
      <h1 className={styles.overviewTitle}>Playground</h1>
      <h1 className={styles.overviewSupport}>Simple snippets, or TIL today.</h1>
      { items.map((item, index) => (
        <Link href={`/playground/${item.slug}`} key={`item--${index}`}>
          <a className={styles.itemCard}>
            <h2 className={styles.itemTitle}>{item.title}</h2>
            <p className={styles.itemDescription}>
              { item.seoTitle }
            </p>
            <div className={styles.itemTaglist}>
              <Icon icon={EIcons.Tag} width={12} height={12} />
              <p className={styles.itemTags}>{item.tags.join(', ')}</p>
            </div>
          </a>
        </Link>
      )) }
    </main>
    <Footer />
  </>;
};

export default PlaygroundOverview;
